name: Build Google tests and run
on: { push: { paths-ignore: [ 'README.md', 'LICENSE' ] }, workflow_dispatch }
# Configuration
env:
  dirGTest: "ThirdParty/googletest"
  dirBuildGTest: "ThirdParty/googletest/build"
  dirInstallGTest: "ThirdParty/googletest/install"
jobs:
  test-in-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version googleTestLatestRepo
        id: gtest-tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: google/googletest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache googleTestLatestRepo
        uses: actions/cache@v3
        with:
          path: ./${{ env.dirGTest }}
          key: cache-key-gtest-${{ steps.gtest-tag.outputs.release }}
        id: cache-gtest

      - name: Download and build googleTestLatestRepo
        if: steps.cache-gtest.outputs.cache-hit != 'true'
        run: | # bash
          git clone --depth 1 --branch ${{ steps.gtest-tag.outputs.release }} https://github.com/google/googletest.git "${{ env.dirGTest }}"
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX="${{ env.dirInstallGTest }}" -S "${{ env.dirGTest }}" -B "${{ env.dirBuildGTest }}"
          make -C "${{ env.dirBuildGTest }}"
          sudo make -C "${{ env.dirBuildGTest }}" install

      - name: Build tests
        run: | # bash
          cmake \
          -D CMAKE_PREFIX_PATH="${{ env.dirInstallGTest }}" \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DMY_GTEST_INCLUDE_DIRS:STRING=${{ github.workspace }}/${{ env.dirInstallGTest }} \
          -S _msvcStuff/cmake -B _msvcStuff/cmake/build
          make -C _msvcStuff/cmake/build
          
      - name: Run tests
        continue-on-error: true
        run: | # bash
          ./bin/x64/PosixfyPrimitives
